# 첫번째 딥러닝 - 레모네이드 판매량 예측
- 데이터: https://raw.githubusercontent.com/blackdew/ml-tensorflow/master/data/csv/lemonade.csv

In [ ]:
import pandas as pd

레모네이드 = pd.read_csv("https://raw.githubusercontent.com/blackdew/ml-tensorflow/master/data/csv/lemonade.csv")
레모네이드

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48
5  25   50

In [ ]:
독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]

print(독립.shape, 종속.shape)

(6, 1) (6, 1)


In [ ]:
import tensorflow as tf
import pandas as pd

# 데이터를 준비합니다.
import pandas as pd

레모네이드 = pd.read_csv("https://raw.githubusercontent.com/blackdew/ml-tensorflow/master/data/csv/lemonade.csv")
독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]

print(독립.shape, 종속.shape)

(6, 1) (6, 1)
(6, 1) (6, 1)


In [ ]:
# 모델을 준비합니다.
X = tf.keras.Input(shape=[1])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.Model(X, Y)
model.compile(loss="mse")

In [ ]:
# 데이터로 모델을 학습합니다.
model.fit(독립, 종속, epochs=1000)

In [ ]:
# 모델을 이용합니다.
model.predict([[15]])

1/1 [==============================] - 0s 35ms/step


array([[30.162035]], dtype=float32)

In [ ]:
3.65e-04 = 3.65 * 0.0001 # (10**-4)
3.65e+04 = 3.65 * 10000

In [ ]:
model.get_weights()

[array([[1.9772003]], dtype=float32), array([0.5040301], dtype=float32)]

In [ ]:
온도 = 15
판매량 = 1.9772003 * 온도 + 0.5040301
판매량

30.162034600000002

# 두번째 딥러닝 - 보스턴 집값 예측
- 데이터: https://raw.githubusercontent.com/blackdew/ml-tensorflow/master/data/csv/boston.csv

In [1]:
import tensorflow as tf
import pandas as pd

# 데이터를 준비합니다.
보스턴 = pd.read_csv("https://raw.githubusercontent.com/blackdew/ml-tensorflow/master/data/csv/boston.csv")
보스턴.columns

독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]

print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [3]:
보스턴.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

        b  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [ ]:
# 모델을 준비합니다.
X = tf.keras.Input(shape=[13])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.Model(X, Y)
model.compile(loss='mse')

In [ ]:
# 데이터로 모델을 학습합니다.
model.fit(독립, 종속, epochs=500, verbose=0)
model.fit(독립, 종속, epochs=10)

In [ ]:
# 모델을 이용합니다.
model.predict(독립[:5])

In [ ]:
종속[:5]

In [ ]:
w, b = model.get_weights()
print(w, b)

[[-0.08286475]
 [ 0.09206408]
 [-0.05978538]
 [ 2.9017615 ]
 [ 0.88193816]
 [ 2.54053   ]
 [ 0.05422787]
 [-0.64088464]
 [ 0.11448012]
 [-0.00641935]
 [ 0.37551942]
 [ 0.01997861]
 [-0.7009067 ]] [1.3484211]


## 수식 출력해보기

In [ ]:
for a, b in zip([1, 2, 3], ["a", "b", "c"]):
    print(a, b)

1 a
2 b
3 c


In [ ]:
variables = ['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']
weights = [f"{e[0]} * {v}" for e, v in zip(w, variables)]
print("y =", "\n  + ".join(weights), f"\n  + {b[0]}")

y = -0.08286475390195847 * crim
  + 0.09206408262252808 * zn
  + -0.0597853846848011 * indus
  + 2.901761531829834 * chas
  + 0.8819381594657898 * nox
  + 2.54052996635437 * rm
  + 0.05422786623239517 * age
  + -0.6408846378326416 * dis
  + 0.11448012292385101 * rad
  + -0.0064193508587777615 * tax
  + 0.37551942467689514 * ptratio
  + 0.019978608936071396 * b
  + -0.7009066939353943 * lstat 
  + 1.3484210968017578


## 부록: for loop 좀 더 이해하기
- for loop 은 배열에서 순서대로 하나씩 꺼내는 게 전부
- multi assign


In [ ]:
# list 위치값가 같이 이용하기
l = ['cat', 'dog', 'fish']
for  ini, e enumerate(l):
    print(i, e)

print(list(enumerate(l)))

0 cat
1 dog
2 fish
[(0, 'cat'), (1, 'dog'), (2, 'fish')]


In [ ]:
# dictionary key, value 같이 이용하기
d = {'cat': 3, 'dog': 10, 'fish': 5}
for k, v in d.items():
    print(k, v)

print(list(d.items()))

cat 3
dog 10
fish 5
[('cat', 3), ('dog', 10), ('fish', 5)]


In [ ]:
# 여러개 리스트 같은 위치에 있는 value 함께 이용하기
l1 = ['a', 'b', 'c']
l2 = [1, 2, 3]
l3 = ['d', 'e', 'f']

for a, b, c in zip(l1, l2, l3):
    print(a, b, c)

print(list(zip(l1, l2, l3)))

a 1 d
b 2 e
c 3 f
[('a', 1, 'd'), ('b', 2, 'e'), ('c', 3, 'f')]


In [ ]:
for e in [1, 2, 3, 4]:
    print(e)

for e in [[1, 2], [3, 4], [4, 5], [5, 6]]:
    print(e)

# multi assign = tuple, list에서 순서에 맞춰서 assign
a, b = 1, 2
c, d = [1, 2]
print(a)
print(b)
print(c)
print(d)

for a, b in [[1, 2], [3, 4], [4, 5], [5, 6]]:
    print(a, b)

# 세번째 딥러닝 - 아이리스 품종 분류

- 데이터: https://raw.githubusercontent.com/blackdew/ml-tensorflow/master/data/csv/iris.csv

In [2]:
import tensorflow as tf
import pandas as pd

# 데이터를 준비합니다.
아이리스 = pd.read_csv("https://raw.githubusercontent.com/blackdew/ml-tensorflow/master/data/csv/iris.csv")
print(아이리스.shape)

# 원핫인코딩
아이리스 = pd.get_dummies(아이리스)
아이리스.columns

독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종_setosa', '품종_versicolor', '품종_virginica']]

print(독립.shape, 종속.shape)

(150, 5)
(150, 4) (150, 3)


In [ ]:
아이리스

In [ ]:
아이리스.head()
# [5.1, 3.5, 1.4, 0.2] => (4,) = [4]
# [[0, 1],
#  [1, 0]] => (2, 2) = [2, 2]

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [ ]:
# 모델을 준비합니다.
X = tf.keras.Input(shape=[4])
Y = tf.keras.layers.Dense(3, activation="softmax")(X)
model = tf.keras.Model(X, Y)
model.compile(loss="categorical_crossentropy", metrics="accuracy")

model.summary()

Model: "model_8"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_9 (InputLayer)        [(None, 4)]               0         
                                                                 
 dense_6 (Dense)             (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [ ]:
# 데이터로 모델을 학습합니다.
model.fit(독립, 종속, epochs=500, verbose=0)
model.fit(독립, 종속, epochs=10)

In [ ]:
# 모델을 이용합니다.
model.predict(독립[:5])

In [ ]:
model.get_weights()

[array([[ 0.10271311,  0.58027256,  0.64411795],
        [-0.25651854,  0.4333285 ,  0.6976403 ],
        [ 0.89606357,  0.14178061,  0.50273776],
        [ 0.6931826 ,  0.48818374,  0.59754956]], dtype=float32),
 array([0., 0., 0.], dtype=float32)]

## [가정] 품종이 2 class 일때
1. 품종을 0, 1의 값으로 치환.
  - 종속변수가 1개
  - sigmoid, binary_crossentropy 사용
2. 품종을 onehot encoding => [0칼럼, 1칼럼]
  - 종속변수 2개
  - softmax, categorical_crossentropy 사용.

## 저장 & 로딩

In [ ]:
# 저장
model.save("my_model.keras")
# 로딩
mymodel = tf.keras.models.load_model("my_model.keras")
# 모델을 이용합니다.
mymodel.predict(독립[:5])

1/1 [==============================] - 0s 49ms/step


array([[0.00337803, 0.14407234, 0.8525496 ],
       [0.00591688, 0.16245413, 0.83162904],
       [0.00524489, 0.16202097, 0.8327341 ],
       [0.00662201, 0.15653406, 0.8368439 ],
       [0.00325118, 0.14163725, 0.85511154]], dtype=float32)

In [ ]:
# 저장
model.save("my_model")
# 로딩
mymodel = tf.keras.models.load_model("my_model")
# 모델을 이용합니다.
mymodel.predict(독립[:5])

## 함수형 언어
- 파이썬 데이터타입
  - int, float, complex
  - str
  - bool
  - list, dictionary, tuple, set
  - function

In [ ]:
def add(a, b):
    return a + b
# add = lambda a, b: a + b

def mul(a, b):
    return a * b
# mul = lambda a, b: a * b

print(type(add))

def func(f, a, b):
    return f(a, b)

print(func(add, 1, 2))
print(func(add, 3, 5))
print(func(mul, 3, 5))

In [ ]:
# 함수를 전달해서 이용하는 예시
students = [["이숙번", 80, 54], ["김건형", 90, 66], ["박종성", 85, 77]]

def get(x):
    return sum(x[1:])
# get = lambda x: sum(x[1:])

sorted(students, key=get)
sorted(students, key=lambda x: sum(x[1:]))

[['이숙번', 80, 54], ['김건형', 90, 66], ['박종성', 85, 77]]

In [ ]:
# 함수를 반환하는 형태
def call():
    return lambda a, b: a + b

call()(1, 2)

3

## 데코레이터를 활용한 합성함수 사용

In [ ]:
def curry(func):
    def curried(*args, **kwargs):
        if len(args) + len(kwargs) >= func.__code__.co_argcount:
            return func(*args, **kwargs)
        return (lambda *args2, **kwargs2:
            curried(*(args + args2), **dict(kwargs, **kwargs2)))
    return curried

@curry
def foo(a, b, c):
    return a - b - c

In [ ]:
print(foo(1, 2, 3))
print(foo(1)(2))
print(foo(1)(2)(3))

In [ ]:
 f(g(x)) = f*g(x)

## class 아주 약간
- method: 자기가 행동할 동작에 대한 함수 - ()
- property: 들고 있는 속성. 데이터 - () 불필요

In [ ]:
l = [1, 2, 3, 4]
print(type(l))

s = "hello"
print(type(s))

i = 1
print(type(i))

In [ ]:
dir(l)

# 네번째 딥러닝 - 진짜 딥뉴럴넷

In [ ]:
import tensorflow as tf
import pandas as pd

# 데이터를 준비합니다.
보스턴 = pd.read_csv("https://raw.githubusercontent.com/blackdew/ml-tensorflow/master/data/csv/boston.csv")
보스턴.columns

독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax', 'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]

print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [ ]:
# 모델을 준비합니다.
X = tf.keras.Input(shape=[13])
H = tf.keras.layers.Dense(128, activation='swish')(X)
Y = tf.keras.layers.Dense(1)(H)
model = tf.keras.Model(X, Y)
model.compile(loss='mse')

model.summary()

Model: "model_10"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_11 (InputLayer)       [(None, 13)]              0         
                                                                 
 dense_9 (Dense)             (None, 128)               1792      
                                                                 
 dense_10 (Dense)            (None, 1)                 129       
                                                                 
Total params: 1,921
Trainable params: 1,921
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(독립, 종속, epochs=1000)

In [ ]:
model.predict(독립[:5])

1/1 [==============================] - 0s 52ms/step


array([[35.579998],
       [24.87855 ],
       [36.056595],
       [37.469337],
       [33.809433]], dtype=float32)

In [ ]:
종속[:5]